CREATE OR REPLACE VIEW sdx_ti_mdr.vw_mdr_16_tp AS
SELECT
      vw_mdr_15.id_proceso
	, vw_mdr_15.tms_ingesta
	, vw_mdr_15.tms_extraccion_fuente
	, vw_mdr_15.lnin_sec
	, vw_mdr_15.fch_transaccion
	, vw_mdr_15.sid_tx_secuencia
	, vw_mdr_15.cdg_comercio
	, vw_mdr_15.mto_transaccion
	, vw_mdr_15.mto_comision
	, vw_mdr_15.mto_vuelto
	, vw_mdr_15.num_bin_ext
	, vw_mdr_15.cdg_producto_canal_contratado
	, vw_mdr_15.cdg_tipo_transaccion
	, vw_mdr_15.cdg_medio_pago
	, vw_mdr_15.cdg_moneda_iso
	, vw_mdr_15.fch_procesamiento
	, vw_mdr_15.fch_cambio_uf
	, vw_mdr_15.fch_cambio_dolar
	, vw_mdr_15.num_periodo_gestion
	, vw_mdr_15.val_uf
	, vw_mdr_15.val_dolar
	, vw_mdr_15.mto_transaccion_clp
	, vw_mdr_15.mto_transaccion_uf
	, vw_mdr_15.mto_transaccion_usd
	, vw_mdr_15.mto_comision_uf
	, vw_mdr_15.mto_vuelto_uf
	, vw_mdr_15.ttx_tipo_flujo
	, vw_mdr_15.ttx_cod_rubro
	, vw_mdr_15.ttx_cod_moneda_tr
	, vw_mdr_15.ttx_monto_orig
	, vw_mdr_15.ttx_fecha
	, vw_mdr_15.ttx_tipo_tx
	, vw_mdr_15.ttx_tipo_tran
	, vw_mdr_15.ttx_nac_o_ext
	, vw_mdr_15.ttx_marca_bin
	, vw_mdr_15.ttx_tipo_contrato
	, vw_mdr_15.ttx_tipo_tarjeta
	, vw_mdr_15.ttx_medio_pago
	, vw_mdr_15.ttx_emisor
	, vw_mdr_15.ttx_iva_comision
	, vw_mdr_15.lnin_sec_ant
	, vw_mdr_15.identificador_producto
	, vw_mdr_15.partition_year
	, vw_mdr_15.partition_month
	, vw_mdr_15.partition_day
	, vw_mdr_15.mto_transaccion_sin_vuelto
	, vw_mdr_15.mto_transaccion_sin_vuelto_uf
	, vw_mdr_15.cod_cred
	, vw_mdr_15.count_trx
	, vw_mdr_15.rut
	, vw_mdr_15.tipo_conexion
	, vw_mdr_15.cod_rubro
	, vw_mdr_15.emisor_fixed
	, vw_mdr_15.bin
	, vw_mdr_15.medio_pago_pucon
	, vw_mdr_15.marca_fixed
	, vw_mdr_15.emsr_gestion_fixed
	, vw_mdr_15.dsc_marca
	, vw_mdr_15.medio_pago_pucon_fixed
	, vw_mdr_15.medio_pago_pucon_fixed_informe
	, vw_mdr_15.modalidad
	, vw_mdr_15.dsc_marca_fixed
	, vw_mdr_15.dsc_marca_fixed_informe
	, vw_mdr_15.product
	, vw_mdr_15.banco
	, vw_mdr_15.criterio
	, vw_mdr_15.mcc
	, vw_mdr_15.ti_product
	, vw_mdr_15.categoria
	, vw_mdr_15.categoria_especiales
	, vw_mdr_15.categoria_final
	, vw_mdr_15.medio_pago_marca
	, vw_mdr_15.tasa
	, vw_mdr_15.emisor_informe
	, vw_mdr_15.id_informe
	, vw_mdr_15.nombre_informe
	, vw_mdr_15.emisor_informe_finanzas
	, vw_mdr_15.rut_informe_finanzas
	, vw_mdr_15.monto_tasa
	, vw_mdr_15.ti
	, vw_mdr_15.membresia
	, vw_mdr_15.switch_usd
	, vw_mdr_15.switch_usd_promedio
	, vw_mdr_15.grupo
	, vw_mdr_15.psp
	, vw_mdr_15.flg_surcharge
	, vw_mdr_15.cod_mod_ti
	, flg_cap
	, flg_franquicia
	, vw_mdr_15.membresia*vw_mdr_15.mto_transaccion_sin_vuelto_uf membresia_uf
	, (vw_mdr_15.switch_usd*vw_mdr_15.val_dolar)/vw_mdr_15.val_uf switch_uf
	, (vw_mdr_15.switch_usd_promedio*vw_mdr_15.val_dolar)/vw_mdr_15.val_uf switch_uf_promedio
	, (vw_mdr_15.membresia*vw_mdr_15.mto_transaccion_sin_vuelto_uf)+((vw_mdr_15.switch_usd_promedio*vw_mdr_15.val_dolar)/vw_mdr_15.val_uf) costo_marca
FROM sdx_ti_mdr.mdr_15_10_2022_tp vw_mdr_15;