CREATE OR REPLACE VIEW sdx_ti_mdr.vw_mdr_12_tp AS 
SELECT
   	 vw_mdr_11.id_proceso
	, vw_mdr_11.tms_ingesta
	, vw_mdr_11.tms_extraccion_fuente
	, vw_mdr_11.lnin_sec
	, vw_mdr_11.fch_transaccion
	, vw_mdr_11.sid_tx_secuencia
	, vw_mdr_11.cdg_comercio
	, vw_mdr_11.mto_transaccion
	, vw_mdr_11.mto_comision
	, vw_mdr_11.mto_vuelto
	, vw_mdr_11.num_bin_ext
	, vw_mdr_11.cdg_producto_canal_contratado
	, vw_mdr_11.cdg_tipo_transaccion
	, vw_mdr_11.cdg_medio_pago
	, vw_mdr_11.ttx_cod_moneda_tr cdg_moneda_iso
	, vw_mdr_11.fch_procesamiento
	, vw_mdr_11.fch_cambio_uf
	, vw_mdr_11.fch_cambio_dolar
	, vw_mdr_11.num_periodo_gestion
	, vw_mdr_11.val_uf
	, vw_mdr_11.val_dolar
	, vw_mdr_11.mto_transaccion_clp
	, vw_mdr_11.mto_transaccion_uf
	, vw_mdr_11.mto_transaccion_usd
	, vw_mdr_11.mto_comision_uf
	, vw_mdr_11.mto_vuelto_uf
	, vw_mdr_11.ttx_tipo_flujo
	, vw_mdr_11.ttx_cod_rubro
	, vw_mdr_11.ttx_cod_moneda_tr
	, vw_mdr_11.ttx_monto_orig
	, vw_mdr_11.ttx_fecha
	, vw_mdr_11.ttx_tipo_tx
	, vw_mdr_11.ttx_tipo_tran
	, vw_mdr_11.ttx_nac_o_ext
	, vw_mdr_11.ttx_marca_bin
	, vw_mdr_11.ttx_tipo_contrato
	, vw_mdr_11.ttx_tipo_tarjeta
	, vw_mdr_11.ttx_medio_pago
	, vw_mdr_11.ttx_emisor
	, vw_mdr_11.ttx_iva_comision
	, vw_mdr_11.lnin_sec_ant
	, vw_mdr_11.identificador_producto
	, vw_mdr_11.partition_year
	, vw_mdr_11.partition_month
	, vw_mdr_11.partition_day
	, vw_mdr_11.flg_surcharge
	, vw_mdr_11.cod_mod_ti
	, mto_transaccion_sin_vuelto
	, mto_transaccion_sin_vuelto_uf
	, cod_cred
	, count_trx
	, vw_mdr_11.rut
	, vw_mdr_11.tipo_conexion
	, vw_mdr_11.cod_rubro
	, vw_mdr_11.emisor_fixed
	, vw_mdr_11.bin
	, vw_mdr_11.medio_pago_pucon
	, vw_mdr_11.marca_fixed
	, vw_mdr_11.emsr_gestion_fixed
	, vw_mdr_11.dsc_marca
	, vw_mdr_11.medio_pago_pucon_fixed
	, vw_mdr_11.modalidad
	, vw_mdr_11.dsc_marca_fixed
    , vw_mdr_11.product
    , vw_mdr_11.banco
    , vw_mdr_11.criterio
    , vw_mdr_11.mcc	
	, vw_mdr_11.ti_product
	, vw_mdr_11.categoria
    , vw_mdr_11.categoria_especiales	
    , vw_mdr_11.categoria_final
	, vw_mdr_11.flg_cliente_especial
    , CASE WHEN vw_mdr_11.medio_pago_pucon_fixed=6 THEN 5 ELSE vw_mdr_11.medio_pago_pucon_fixed END AS medio_pago_marca
FROM sdx_ti_mdr.vw_mdr_11_tp vw_mdr_11;